In [1]:
import torch
import numpy as np

In [2]:
a = torch.randn(2, 3)
a.type()

'torch.FloatTensor'

In [3]:
type(a)

torch.Tensor

In [4]:
isinstance(a, torch.FloatTensor) #判断数据类型isinstance

True

In [5]:
isinstance (a, torch.LongTensor)#判断用

False

## 0维度张量
- dim = 0 rank = 0 是scalse标量
- 标量的shpae是‘[]’
- dim = 1就是向量

In [6]:
torch.tensor(1.) #1. = 1.0

tensor(1.)

In [7]:
torch.tensor(1.3)

tensor(1.3000)

In [8]:
a = torch.tensor(2.2)#标量

In [9]:
a.shape #0维度结构，[]

torch.Size([])

In [10]:
len(a.shape) #压平后的长度

0

In [11]:
a.size() #同shape

torch.Size([])

# 1维度向量（注意区别标量0维）
- a.dim()求维度 = 1
- 使用numpy类型产生tensor
- pytorch 0.3版本之后才有0维度数据
- numel()：统计元素数量

In [12]:
#1维向量，结果又「」
torch.tensor([1.1])

tensor([1.1000])

In [13]:
#0维向量，注意对比结果,没有“【】”
torch.tensor(1.1)

tensor(1.1000)

In [14]:
torch.FloatTensor(1) #注意输入shape

tensor([0.])

In [15]:
torch.FloatTensor(2,3) #产生2x3的矩阵

tensor([[1.1210e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

# 创建tensor对象
- 尽量用tensor（小写）喂数据
- 尽量用Tensor（大写）喂shape（IntTensor FloatTensor ByteTensor DoubleTensor）
- Tensor即可以输入数据集合，也可以输入shape，容易混淆，建议只用于输入数据shape
- numel()得到元素个数numble of element

In [16]:
a = np.array([2, 3,3])

In [17]:
a

array([2, 3, 3])

In [18]:
b = torch.from_numpy(a)

In [19]:
b.size()

torch.Size([3])

In [20]:
b.shape #与size等效

torch.Size([3])

In [21]:
b.numel() #元素数量

3

In [22]:
b.type() #根据np中色数据类型直接设置默认

'torch.LongTensor'

In [23]:
b

tensor([2, 3, 3])

## 大小写的区别Tensor / tensor区别
- 小写tensor：加载数据
- 大写Tensor：设置shape，将tensor数据随机填充，做容器


'''flow
st=>start: Start
op=>operation: Your Operation
cond=>condition: Yes or No?
e=>end

st->op->cond
cond(yes)->e
cond(no)->op
'''


In [24]:
#大写Tensor创建tensor 2x3,填充数据为随机数据--->容器
torch.FloatTensor(2,3)

tensor([[8.4078e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.5695e-43]])

In [25]:
#小写tensor,从list中创建
t = torch.tensor([[2., 3.2],[1., 22.3]])

In [26]:
t.shape

torch.Size([2, 2])

In [27]:
t.type

<function Tensor.type>

In [28]:
i_tensor = torch.IntTensor(1,3, 28, 28)

In [29]:
i_tensor.size()


torch.Size([1, 3, 28, 28])

In [30]:
i_tensor.numel()

2352

## 非初始化构建

In [31]:
torch.empty(1) #1维张量

tensor([0.])

In [32]:
torch.Tensor(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [33]:
torch.IntTensor(2, 3) #数据内容随机，shape指定

tensor([[          6,           0,           0],
        [          0,           0, -1610612736]], dtype=torch.int32)

In [34]:
torch.FloatTensor(2, 3)#数据内容随机，shape指定

tensor([[1.4013e-44, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

## 2.2 修改默认元素类型
- set_defalutl_tensor_type()
- DoubleTensor FloatTensor IntTensor ByteTensor

In [35]:
torch.tensor([1.2, 3]).type()

'torch.FloatTensor'

In [36]:
#修改成double类型
torch.set_default_tensor_type(torch.DoubleTensor)

In [37]:
torch.tensor([1.2, 3]).type()

'torch.DoubleTensor'

In [38]:
torch.tensor([1])

tensor([1])

# 随机初始化（推荐使用）
# rand / rand_like / randint

In [39]:
torch.rand(3, 3) #构建3x3 的矩阵结构

tensor([[0.6456, 0.3905, 0.9644],
        [0.0144, 0.4865, 0.1375],
        [0.6753, 0.7298, 0.5004]])

In [40]:
a = torch.rand(3, 3)

In [41]:
torch.rand_like(a)

tensor([[0.1712, 0.0223, 0.2427],
        [0.0393, 0.9697, 0.7457],
        [0.9465, 0.0288, 0.6904]])